source 'https://rubygems.org'

gem 'rails', '3.2.12'

gem 'activerecord-jdbcsqlite3-adapter'

gem 'jruby-openssl'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyrhino'
  gem 'uglifier', '>= 1.0.3'
  gem 'zurb-foundation'
end

group :development do
  gem "warbler"
end

group :development, :test do
  gem 'rspec-rails'
end


gem 'jquery-rails'

# gem 'bcrypt-ruby', '~> 3.0.0'



